[package]
name = "tpl_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = "0.14.1"
clap = { version = "4.5.34", features = ["derive"] }
gctex = "0.3.12"
image = "0.25.5"
strum = { version = "0.27.1", features = ["derive"] }
